import type { NextPage } from "next";
import Head from "next/head";
import { HomePageContainer } from "../styles/pages/homePage";
import { useRouter } from "next/router";
import { signIn, signOut, useSession } from "next-auth/react";

const Home: NextPage = () => {
  const router = useRouter();
  function goChallenge() {
    router.push("/challenges/vitejs-vite-a52dad");
  }

  const { data, status } = useSession();

  async function handleSignIn() {
    await signIn("github");
  }

  async function handleSignOut() {
    await signOut();
  }

  return (
    <HomePageContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={goChallenge}>Go to challenge</button>
      {status === "authenticated" ? (
        <>
          <button onClick={handleSignOut}>SignOut</button>
          <div>
            <img src={data.user?.image} />
            <strong>{data.user?.name}</strong>
            <p>{data.user?.email}</p>
          </div>
        </>
      ) : (
        <button onClick={handleSignIn}>SignIn</button>
      )}
    </HomePageContainer>
  );
};

export default Home;
