import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { HomePageContainer } from "../styles/pages/homePage";
import { Header } from "components/Header";
import { Challenges } from "components/Challenges";
import { api } from "lib/axios";
import { IChallenge } from "interfaces/challenges.interface";

interface HomeProps {
  challenges: IChallenge[];
}

const Home: NextPage<HomeProps> = ({ challenges }) => {
  return (
    <HomePageContainer>
      <Head>
        <title>Challenges | upskill.code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Challenges challenges={challenges} />
      {/* <button onClick={goChallenge}>Go to challenge</button>
      {status === "authenticated" ? (
        <>
          <button onClick={handleSignOut}>SignOut</button>
          <div>
            <img src={data.user?.image} />
            <strong>{data.user?.name}</strong>
            <p>{data.user?.email}</p>
          </div>
        </>
      ) : (
        <button onClick={handleSignIn}>SignIn</button>
      )} */}
    </HomePageContainer>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await api.get("/challenges");

  return {
    props: {
      challenges: data,
    },

    revalidate: 86400,
  };
};

export default Home;
